ability = {
	'Overgrow','Overgrow',
	'Overgrow','Overgrow',
	'Chlorophyll','Overgrow',
	'Blaze','Blaze',
	'Blaze','Blaze',
	'Blaze','Blaze',
	'Torrent','Torrent',
	'Torrent','Torrent',
	'Torrent','Torrent',
	'Shield Dust','Shield Dust',
	'Shed Skin','Shed Skin',
	'Compound Eyes','Compound Eyes',
	'Shield Dust','Shield Dust',
	'Shed Skin','Shed Skin',
	'Swarm','Swarm',
	'Keen Eye','Keen Eye',
	'Keen Eye','Keen Eye',
	'Early Bird','Early Bird',
	'Run Away','Run Away',
	'Guts','Guts',
	'Keen Eye','Keen Eye',
	'Early Bird','Early Bird',
	'Intimidate','Shed Skin',
	'Intimidate','Shed Skin',
	'Lightning Rod','Lightning Rod',
	'Lightning Rod','Lightning Rod',
	'Sand Veil','Sand Veil',
	'Sand Veil','Sand Veil',
	'Poison Point','Poison Point',
	'Poison Point','Poison Point',
	'Poison Point','Poison Point',
	'Poison Point','Poison Point',
	'Poison Point','Poison Point',
	'Poison Point','Poison Point',
	'Cute Charm','Cute Charm',
	'Cute Charm','Cute Charm',
	'Pressure','Pressure',
	'Pressure','Pressure',
	'Cute Charm','Cute Charm',
	'Cute Charm','Cute Charm',
	'Inner Focus','Inner Focus',
	'Inner Focus','Inner Focus',
	'Chlorophyll','Chlorophyll',
	'Chlorophyll','Chlorophyll',
	'Chlorophyll','Chlorophyll',
	'Effect Spore','Effect Spore',
	'Effect Spore','Effect Spore',
	'Compound Eyes','Shield Dust',
	'Compound Eyes','Shield Dust',
	'Arena Trap','Sand Veil',
	'Arena Trap','Sand Veil',
	'Limber','Limber',
	'Limber','Limber',
	'Swift Swim','Oblivious',
	'Swift Swim','Oblivious',
	'Vital Spirit','Vital Spirit',
	'Vital Spirit','Vital Spirit',
	'Intimidate','Run Away',
	'Intimidate','Blaze',
	'Swift Swim','Swift Swim',
	'Swift Swim','Swift Swim',
	'Swift Swim','Swift Swim',
	'Synchronize','Inner Focus',
	'Synchronize','Inner Focus',
	'Synchronize','Inner Focus',
	'Guts','Guts',
	'Guts','Guts',
	'Guts','Guts',
	'Chlorophyll','Chlorophyll',
	'Chlorophyll','Chlorophyll',
	'Chlorophyll','Chlorophyll',
	'Clear Body','Liquid Ooze',
	'Clear Body','Liquid Ooze',
	'Rock Head','Sturdy',
	'Rock Head','Sturdy',
	'Rock Head','Sturdy',
	'Flame Body','Run Away',
	'Flame Body','Run Away',
	'Oblivious','Own Tempo',
	'Shell Armor','Own Tempo',
	'Magnet Pull','Sturdy',
	'Magnet Pull','Sturdy',
	'Keen Eye','Inner Focus',
	'Early Bird','Run Away',
	'Early Bird','Run Away',
	'Thick Fat','Thick Fat',
	'Swift Swim','Thick Fat',
	'Poison Point','Sticky Hold',
	'Poison Point','Sticky Hold',
	'Shell Armor','Shell Armor',
	'Shell Armor','Shell Armor',
	'Levitate','Levitate',
	'Levitate','Levitate',
	'Levitate','Levitate',
	'Rock Head','Sturdy',
	'Insomnia','Insomnia',
	'Insomnia','Insomnia',
	'Hyper Cutter','Shell Armor',
	'Hyper Cutter','Shell Armor',
	'Static','Static',
	'Static','Static',
	'Chlorophyll','Chlorophyll',
	'Chlorophyll','Chlorophyll',
	'Lightning Rod','Rock Head',
	'Lightning Rod','Rock Head',
	'Limber','Limber',
	'Guts','Guts',
	'Own Tempo','Oblivious',
	'Levitate','Levitate',
	'Levitate','Levitate',
	'Lightning Rod','Rock Head',
	'Lightning Rod','Rock Head',
	'Natural Cure','Serene Grace',
	'Chlorophyll','Chlorophyll',
	'Early Bird','Early Bird',
	'Swift Swim','Swift Swim',
	'Poison Point','Poison Point',
	'Swift Swim','Water Veil',
	'Swift Swim','Water Veil',
	'Natural Cure','Illuminate',
	'Natural Cure','Illuminate',
	'Own Tempo','Own Tempo',
	'Swarm','Swarm',
	'Oblivious','Oblivious',
	'Static','Static',
	'Flame Body','Flame Body',
	'Intimidate','Hyper Cutter',
	'Intimidate','Intimidate',
	'Swift Swim','Swift Swim',
	'Intimidate','Intimidate',
	'Shell Armor','Shell Armor',
	'Shadow Tag','Shadow Tag',
	'Run Away','Run Away',
	'Swift Swim','Swift Swim',
	'Static','Static',
	'Flame Body','Flame Body',
	'Trace','Trace',
	'Swift Swim','Shell Armor',
	'Swift Swim','Shell Armor',
	'Swift Swim','Battle Armor',
	'Swift Swim','Battle Armor',
	'Rock Head','Pressure',
	'Guts','Thick Fat',
	'Pressure','Pressure',
	'Pressure','Pressure',
	'Pressure','Pressure',
	'Shed Skin','Shed Skin',
	'Shed Skin','Shed Skin',
	'Thick Fat','Shed Skin',
	'Pressure','Run Away',
	'Synchronize','Synchronize',
	'Overgrow','Overgrow',
	'Overgrow','Overgrow',
	'Thick Fat','Overgrow',
	'Blaze','Blaze',
	'Blaze','Blaze',
	'Blaze','Blaze',
	'Torrent','Torrent',
	'Torrent','Torrent',
	'Battle Armor','Torrent',
	'Early Bird','Keen Eye',
	'Early Bird','Keen Eye',
	'Insomnia','Keen Eye',
	'Insomnia','Keen Eye',
	'Early Bird','Swarm',
	'Early Bird','Swarm',
	'Insomnia','Swarm',
	'Insomnia','Swarm',
	'Inner Focus','Inner Focus',
	'Volt Absorb','Illuminate',
	'Volt Absorb','Illuminate',
	'Static','Static',
	'Cute Charm','Cute Charm',
	'Cute Charm','Cute Charm',
	'Serene Grace','Hustle',
	'Serene Grace','Hustle',
	'Early Bird','Synchronize',
	'Early Bird','Synchronize',
	'Static','Static',
	'Static','Static',
	'Static','Static',
	'Chlorophyll','Chlorophyll',
	'Huge Power','Thick Fat',
	'Huge Power','Thick Fat',
	'Rock Head','Sturdy',
	'Swift Swim','Swift Swim',
	'Chlorophyll','Chlorophyll',
	'Chlorophyll','Chlorophyll',
	'Chlorophyll','Chlorophyll',
	'Vital Spirit','Own Tempo',
	'Chlorophyll','Chlorophyll',
	'Chlorophyll','Chlorophyll',
	'Speed Boost','Compound Eyes',
	'Water Absorb','Oblivious',
	'Water Absorb','Oblivious',
	'Synchronize','Synchronize',
	'Synchronize','Synchronize',
	'Insomnia','Insomnia',
	'Natural Cure','Own Tempo',
	'Levitate','Levitate',
	'Levitate','Levitate',
	'Shadow Tag','Shadow Tag',
	'Early Bird','Inner Focus',
	'Rough Skin','Sturdy',
	'Shell Armor','Sturdy',
	'Serene Grace','Run Away',
	'Hyper Cutter','Sand Veil',
	'Rock Head','Sturdy',
	'Intimidate','Run Away',
	'Intimidate','Intimidate',
	'Swift Swim','Poison Point',
	'Swarm','Swarm',
	'Shell Armor','Sturdy',
	'Guts','Swarm',
	'Inner Focus','Keen Eye',
	'Guts','Guts',
	'Guts','Guts',
	'Flame Body','Magma Armor',
	'Flame Body','Flame Body',
	'Oblivious','Oblivious',
	'Thick Fat','Oblivious',
	'Natural Cure','Hustle',
	'Hustle','Hustle',
	'Suction Cups','Suction Cups',
	'Vital Spirit','Hustle',
	'Swift Swim','Water Veil',
	'Keen Eye','Sturdy',
	'Early Bird','Early Bird',
	'Intimidate','Early Bird',
	'Swift Swim','Swift Swim',
	'Cute Charm','Cute Charm',
	'Battle Armor','Sturdy',
	'Trace','Trace',
	'Intimidate','Intimidate',
	'Own Tempo','Own Tempo',
	'Guts','Guts',
	'Intimidate','Guts',
	'Oblivious','Oblivious',
	'Static','Static',
	'Flame Body','Flame Body',
	'Thick Fat','Thick Fat',
	'Natural Cure','Serene Grace',
	'Pressure','Pressure',
	'Pressure','Pressure',
	'Pressure','Pressure',
	'Guts','Guts',
	'Shed Skin','Shed Skin',
	'Intimidate','Intimidate',
	'Pressure','Run Away',
	'Pressure','Run Away',
	'Natural Cure','Natural Cure',
	' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',
	'Overgrow','Overgrow',
	'Overgrow','Overgrow',
	'Overgrow','Overgrow',
	'Speed Boost','Blaze',
	'Blaze','Blaze',
	'Blaze','Blaze',
	'Torrent','Torrent',
	'Torrent','Torrent',
	'Swift Swim','Torrent',
	'Run Away','Run Away',
	'Intimidate','Intimidate',
	'Guts','Guts',
	'Guts','Guts',
	'Shield Dust','Shield Dust',
	'Shed Skin','Shed Skin',
	'Swarm','Swarm',
	'Shed Skin','Shed Skin',
	'Shield Dust','Shield Dust',
	'Swift Swim','Rain Dish',
	'Swift Swim','Rain Dish',
	'Swift Swim','Rain Dish',
	'Chlorophyll','Early Bird',
	'Chlorophyll','Early Bird',
	'Chlorophyll','Early Bird',
	'Compound Eyes','Compound Eyes',
	'Speed Boost','Speed Boost',
	'Wonder Guard','Wonder Guard',
	'Guts','Guts',
	'Guts','Guts',
	'Effect Spore','Effect Spore',
	'Effect Spore','Effect Spore',
	'Own Tempo','Own Tempo',
	'Keen Eye','Keen Eye',
	'Swift Swim','Keen Eye',
	'Swift Swim','Swift Swim',
	'Intimidate','Intimidate',
	'Pressure','Oblivious',
	'Pressure','Oblivious',
	'Cute Charm','Cute Charm',
	'Cute Charm','Cute Charm',
	'Color Change','Color Change',
	'Levitate','Levitate',
	'Levitate','Levitate',
	'Battle Armor','Sturdy',
	'White Smoke','Shell Armor',
	'Pressure','Pressure',
	'Oblivious','Oblivious',
	'Swift Swim','Oblivious',
	'Swift Swim','Swift Swim',
	'Shell Armor','Hyper Cutter',
	'Shell Armor','Hyper Cutter',
	'Swift Swim','Swift Swim',
	'Swift Swim','Marvel Scale',
	'Rough Skin','Rough Skin',
	'Rough Skin','Rough Skin',
	'Arena Trap','Hyper Cutter',
	'Levitate','Levitate',
	'Levitate','Levitate',
	'Thick Fat','Guts',
	'Thick Fat','Guts',
	'Static','Lightning Rod',
	'Intimidate','Lightning Rod',
	'Oblivious','Oblivious',
	'Magma Armor','Magma Armor',
	'Thick Fat','Thick Fat',
	'Thick Fat','Thick Fat',
	'Rain Dish','Thick Fat',
	'Sand Veil','Sand Veil',
	'Sand Veil','Sand Veil',
	'Inner Focus','Inner Focus',
	'Intimidate','Inner Focus',
	'Levitate','Levitate',
	'Levitate','Levitate',
	'Huge Power','Thick Fat',
	'Thick Fat','Own Tempo',
	'Thick Fat','Own Tempo',
	'Plus','Plus',
	'Minus','Minus',
	'Intimidate','Hyper Cutter',
	'Pure Power','Pure Power',
	'Pure Power','Pure Power',
	'Natural Cure','Natural Cure',
	'Natural Cure','Natural Cure',
	'Shadow Tag','Natural Cure',
	'Levitate','Levitate',
	'Pressure','Keen Eye',
	'Natural Cure','Poison Point',
	'Truant','Truant',
	'Vital Spirit','Vital Spirit',
	'Truant','Truant',
	'Liquid Ooze','Sticky Hold',
	'Liquid Ooze','Sticky Hold',
	'Chlorophyll','Chlorophyll',
	'Vital Spirit','Vital Spirit',
	'Vital Spirit','Vital Spirit',
	'Vital Spirit','Vital Spirit',
	'Shell Armor','Shell Armor',
	'Swift Swim','Swift Swim',
	'Swift Swim','Swift Swim',
	'Pressure','Pressure',
	'Insomnia','Insomnia',
	'Insomnia','Insomnia',
	'Shed Skin','Shed Skin',
	'Guts','Immunity',
	'Rock Head','Swift Swim',
	'Rock Head','Sturdy',
	'Rock Head','Sturdy',
	'Rock Head','Sturdy',
	'Forecast','Forecast',
	'Swarm','Swarm',
	'Oblivious','Oblivious',
	'Suction Cups','Suction Cups',
	'Suction Cups','Suction Cups',
	'Battle Armor','Battle Armor',
	'Battle Armor','Battle Armor',
	'Synchronize','Synchronize',
	'Synchronize','Synchronize',
	'Synchronize','Trace',
	'Rock Head','Rock Head',
	'Rock Head','Rock Head',
	'Intimidate','Intimidate',
	'Clear Body','Clear Body',
	'Clear Body','Clear Body',
	'Clear Body','Clear Body',
	'Clear Body','Clear Body',
	'Clear Body','Clear Body',
	'Clear Body','Clear Body',
	'Pressure','Run Away',
	'Rock Head','Run Away',
	'Pressure','Run Away',
	'Levitate','Levitate',
	'Levitate','Levitate',
	'Serene Grace','Serene Grace',
	'Pressure','Pressure',
	'Levitate','Levitate',}